### ISSUE TITLE
Explain Assert_v2

### ISSUE THREAD

**Issue by cokes518** [helium/docs#304]
Add documentation to explain the new Assert_v2 transaction that supports remote assert, adding antenna gain and antenna elevation.

Helium App v3.1.0 will officially support remote assert, where a Hotspot owner can update the location of their hotspot without bluetooth pairing as the blockchain code has removed "gateway_signature" as a required signer for the transaction.

Included in assert_v2 is allowing users to input antenna gain (expressed in dBi) and elevation (denoted as "Height" in the app, measured in meters, relative to above ground level). an assert_v2 transaction with ONLY gain and elevation change will be charged the typical transaction fee (55,000 DC), whereas a full location update will be the standard $10 in DC.

**Comment by cascading-jox** [comment]
I would like to add this to the documentation. Is there any specific section where it should be added? 

I assume this should be a more technical documentation about the new assert transaction and what those new inputs are/will be used for. Not sure where you would put a section like that though since the only place which seems to describe the process somewhat is in the [data only hotspot section](https://docs.helium.com/mine-hnt/data-only-hotspots/#transactions--cost). 

I was thinking to use [this](https://discordapp.com/channels/404106811252408320/730243594707009608/863150628485726208) as the source.
